name: Compiler

on:
  push:
    branches: [ rebase ]
  pull_request:
    branches: [ rebase ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Toolchains
      run: |
       git clone https://github.com/kdrag0n/proton-clang --depth=1 clang
       export PATH="$(pwd)/clang/bin:"${PATH}
    - name: Making Defconfig
      run: make ARCH=arm64 CC=clang CROSS_COMPILE=aarch64-linux-gnu- vendor/sm8150-perf_defconfig
    - name: Making Image
      run: make ARCH=arm64 CC=clang CROSS_COMPILE=aarch64-linux-gnu-
    - name: Upload Build
      uses: actions/upload-artifact@v2.1.4
      with:
        name: Image.gz
        path: arch/arm64/boot/Image.gz
